#%RAML 1.0 NamedExample


value:
-
  id: "1234"
  firstName: "Sunny"
  lastName: "Kootgal"
  address: "123 Percy St, Ingleburn "
  postal: "2565"
  country: "Australia"
  miles: 543
  creationDate: 2019-08-21T04:34:41.098Z
  accType: "personal"
-
  id: "8877"
  firstName: "Josh"
  lastName: "Sarah"
  address: "21 Durbin St, NSW"
  postal: "2576"
  country: "Australia"
  miles: 1234
  creationDate: 2018-12-09T21:53:12.127Z
  accType: "business"  


  
  
 